# _config.yml

title: Your Data Analyst Portfolio
author: Your Name
description: A portfolio site for showcasing your data analysis work.
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/
paginate: 10

# Add any additional configuration here
